# https://taskfile.dev

version: '3'

vars:
  VERSION: 0.0.3

tasks:
  build:
    cmds:
      - go build ./...
    silent: true
  test:
    cmds:
      - go test ./...
    silent: true
  format: 
    cmds:
      - gofmt -w -s .
    silent: true
  vet: 
    cmds:
      - go vet ./...
    silent: true
  staticcheck: 
    cmds:
      - staticcheck ./...
    silent: true
  tidy: 
    cmds:
      - go mod tidy
    silent: true
  libpub:
    cmds:
      - git push origin
      - git tag v{{.VERSION}}
      - git push --tags
      - GOPROXY=proxy.golang.org go list -m github.com/bketelsen/toolbox@v{{.VERSION}}
  release-snapshot:
    cmds:
      - goreleaser release --snapshot --clean
    silent: true
  release-check:
    cmds:
      - goreleaser check
    silent: true