# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
project_name: toolgen
before:
  hooks:
    - go mod tidy

gomod:
  proxy: true

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: toolgen
    id: toolgen
    main: ./toolgen/main.go
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X github.com/bketelsen/toolbox/toolgen/cmd.date={{ .CommitDate }} -X github.com/bketelsen/toolbox/toolgen/cmd.builtBy=goreleaser-pro -X github.com/bketelsen/toolbox/toolgen/cmd.version={{.Version}} -X github.com/bketelsen/toolbox/toolgen/cmd.commit={{.Commit}} -X github.com/bketelsen/toolbox/toolgen/cmd.treeState={{ .IsGitDirty }}'


archives:
  - formats: [ 'tar.gz' ]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: "^.*feat\\(deps\\)*:+.*$"
      order: 300
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: "Documentation updates"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999

release:
  footer: |
    **Full Changelog**: https://github.com/bketelsen/toolbox/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## What to do next?

    - Read the [documentation](https://bketelsen.github.io/toolbox/)
    - Install the [toolgen cli tool](https://bketelsen.github.io/toolbox/)
