# https://taskfile.dev

version: '3'

vars:
  VERSION: 0.0.1

tasks:
  build:
    desc: Build the application
    summary: |
      Builds the application and embeds the version information in the binary
    cmds:
      - go build -o taskdoc -ldflags '-s -w -X taskdoc/cmd.version={{.VERSION}}-dev' main.go
    silent: true

  test:
    desc: Run all tests
    summary: Run all tests
    cmds:
      - go test ./...
    silent: true

  format:
    desc: Format all Go source
    summary: Format all Go source
    cmds:
      - gofmt -w -s .
    silent: true

  vet:
    desc: Run go vet on sources
    summary: Run go vet on sources
    cmds:
      - go vet ./...
    silent: true

  staticcheck:
    desc: Run go staticcheck
    summary: Run go staticcheck
    cmds:
      - staticcheck ./...
    silent: true

  tidy:
    desc: Run go mod tidy 
    summary: Run go mod tidy 
    cmds:
      - go mod tidy
    silent: true

  checks:
    desc: Run all go checks
    summary: Runs staticcheck, vet, test, format, and tidy
    cmds:
      - task staticcheck
      - task vet
      - task test
      - task format
      - task tidy
    silent: true

  tools:
    desc: Install required tools
    summary: Installs the `starter` command line tool
    cmds:
      - go install github.com/bketelsen/toolbox/starter@latest

  snapshot:
    desc: Run goreleaser in snapshot mode
    summary: | 
      Run goreleaser in snapshot mode, suitable for testing the release process
    cmds:
      - goreleaser release --snapshot --clean
    silent: true

  release-check:
    desc: Run goreleaser check
    summary: |
      Run goreleaser check to verify the release configuration
    cmds:
      - goreleaser check
    silent: true

  publish:
    desc: Push and tag at .VERSION
    summary: |
      Push and tag at taskfile variable "VERSION", which triggers the release process on GitHub. 
      Update the version in the taskfile and commit the change before running this task.
    cmds:
      - git push origin
      - git tag v{{.VERSION}}
      - git push --tags

  direnv:
    desc: Add direnv hook to your bashrc
    cmds:
      - direnv hook bash >> ~/.bashrc
    silent: true

  goreleaser:
    desc: Install goreleaser on debian derivatives
    cmds:
      - wget https://github.com/goreleaser/goreleaser-pro/releases/download/v2.7.0-pro/goreleaser-pro_2.7.0_amd64.deb
      - sudo dpkg -i goreleaser-pro_2.7.0_amd64.deb
      - rm goreleaser-pro_2.7.0_amd64.deb
    silent: true

