# https://taskfile.dev

version: '3'

vars:
  VERSION: 0.0.1

tasks:
 
  site:
    desc: Run hugo dev server
    cmds:
      - task: :build
      - task: :generate
      - hugo server --buildDrafts --disableFastRender